### ISSUE TITLE
How to install in Debian 9 (stretch)

### ISSUE THREAD

**Issue by magster95** [jonathanunderwood/outsider#10]
Here are instructions to install in Debian 9:

sudo apt-get install git python3-pyqt5 python3-usb python3-setuptools
git clone https://github.com/jonathanunderwood/outsider.git
sudo  python3 setup.py install
sudo cp -a blackstar-id.rules /etc/udev/rules.d/69-blackstar-id.rules
sudo udevadm control --reload-rules

And it's fine. Thank you for this great work !

**Comment by jonathanunderwood** [comment]
Great, thanks, will add to README.
